default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: postgres
      password: password
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production
